### ISSUE TITLE
Unable to download, no seeds

### ISSUE THREAD

**Issue by ojalar** [RoboticsBUT/Brno-Urban-Dataset#6]
Hey,
I'm trying to download recording 3_1_1_1, but I'm getting zero seeds. Are the files available at the moment, or is the problem in my end?

**Comment by rem821** [comment]
Hi,
we apologize for the inconvinience caused by the unreliable seeding. We're battling our university policies concerning opening ports outside of our organization. In the past we've also used one of the VPN services that allowed for port forwading, but they dropped support for it since. We've now bought a 3 year license from PIA VPN and it should smoothly from now on. Either way, If you're really relying on having this dataset, we would suggest downloading it entirely.
