### ISSUE TITLE
Some questions about label categories

### ISSUE THREAD

**Issue by mihui20** [RoboticsBUT/Brno-Urban-Dataset#8]
Hello, thank you for providing the dataset, which has been very helpful to me.
 I want to ask a question. I did not find any information on the category names corresponding to the labels in the program or dataset you provided.
 Please let me know in which file this information is located.

**Comment by nilushacj** [comment]
Hi @mihui20 . May I know if you downloaded the dataset recently (i.e. within the past year or so)? If so, did you not have any issues with lack of seeds (because I am not able to download it via the torrent link)? 

Lastly, would it somehow be possible for you to kindly re-share the dataset by an alternative way so that I can use it for my doctoral research? Thank you!

**Comment by rem821** [comment]
Hi! Thanks for the query. 
The labels correspond to how the YoloV5 official models were labeled: https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml

@nilushacj https://github.com/Robotics-BUT/Brno-Urban-Dataset/issues/6 see this issue, we've sadly had an outage as we weren't been able to seed outside our organization due to its policies. We recommend to download as much of the dataset now as possible. It looks promising with the uptime now, but we sadly cannot guarantee its going to last years.
